### ISSUE TITLE
Error 23: ) does not have a value

### ISSUE THREAD

**Issue by lambslamchops** [ndepaola/mtg-autoproxy#27]
I keep returning the titled error whenever I run the proxy_target script. If I run the proxy_all script I get no response. The get_card_info.py also returns this response: The document “get_card_info.py” could not be opened. IDLE cannot open files in the “Python Script” format. I tried running the permissions fix suggested in the FAQ but it can't locate the card.json. I also tried redownloading the repo but to no avail.
I'm using python 3.9.6 on a mac 11.3.1.

**Comment by ndepaola** [comment]
hello - the script should automatically create card.json in the scripts folder when you run either proxy script, so it sounds like the command isn't working on your system. can you try pulling the refactor branch and run it again? if it fails to successfully run the python script, it'll now show you an error with the command it tried, which may help you debug. the python script also now no longer depends on any nonstandard libraries in case you were missing scrython or something.

**Comment by lambslamchops** [comment]
Now it tells me error 24: proxy is not a function. It must not see the proxy.jsx in the same folder.

**Comment by ndepaola** [comment]
hmm - on that branch the main function that `proxy_target` and `proxy_all` calls is `proxy_new()`, so i'm not sure why you're hitting that error w/o seeing your setup. did you download the refactor branch to a different folder on your computer so you're starting with a blank slate?

**Comment by lambslamchops** [comment]
Maybe I did it wrong, what do you mean by the refactor branch?

**Comment by ndepaola** [comment]
sorry, i should've clarified - i've been updating the project over here https://github.com/ndepaola/mtg-autoproxy/tree/refactor  over the last week, but it's still a work in progress, hence why those changes aren't in the main version of the project yet. however i suspect i fixed the root cause of the issue you're experiencing on that branch. could you try downloading the code from that branch to a separate folder on your computer and run the scripts again?

**Comment by lambslamchops** [comment]
Okay now it returns: Error 48: File or folder does not exist. 
Line: 1
->  #include "scripts/proxy.jsx";

**Comment by lambslamchops** [comment]
Sorry I rearranged the folders and it now returns 
Line: 5
->  #include "..\\settings.jsx";

**Comment by ndepaola** [comment]
understood - i'm downloading photoshop on my mac to test #include's and will get back to you when i've fixed it, it's probably a simple fix

**Comment by lambslamchops** [comment]
I changed the 5th line to #include "settings.jsx"; and that seemed to work,
now it seems to have an issue running the get_card_info.py script
I changed the line to say "python3" since that's how mac needs it to read but it still doesn't like the command when the script runs it, but if I manually type it, the terminal looks like this `python3 /Users/adamryan/Desktop/working_directory/mtg-autoproxy-refactor/scripts/get_card_info.py "plains" 
Searching Scryfall for: plains... and done! Saving JSON... and done!`
<img width="261" alt="Screen Shot 2021-08-02 at 1 21 59 AM" src="https://user-images.githubusercontent.com/88264737/127828815-4ffcc0a5-d12f-411d-95c1-414b9e9aad7f.png">

**Comment by ndepaola** [comment]
just tested this on my mac and i encountered the same issue - the terminal command was working from photoshop but it was failing to read the file - try replacing `\\` with `/` in the json file path in `constants.jsx`. i'll do some more testing and see if it works with forward slashes on windows too, and update the rest of the project so it works on both platforms if so

**Comment by ndepaola** [comment]
should be fixed now

**Comment by lambslamchops** [comment]
<img width="258" alt="Screen Shot 2021-08-02 at 8 51 54 AM" src="https://user-images.githubusercontent.com/88264737/127889362-91e71d5e-1c2a-403f-bb0e-1b1bc47b332d.png">
Sadly, It still does not work. It returns this error now. I have all the templates downloaded so it must be something else.
<img width="181" alt="Screen Shot 2021-08-02 at 8 54 04 AM" src="https://user-images.githubusercontent.com/88264737/127889592-8af8c59d-4d78-4941-b2f6-d2ed733bd0fa.png">

**Comment by ndepaola** [comment]
what card are you running the script with? I haven't re-implemented transform, mdfc, or planar cards on the refactor branch yet - maybe try with a normal-border card?

**Comment by lambslamchops** [comment]
a basic plains

**Comment by lambslamchops** [comment]
I got it to work! Thanks for everything!

**Comment by lambslamchops** [comment]
I do have to say the normal proxy works fine but it appears the other settings don't work. The new proxy.jsx file also has some missing bits like specified_template isn't defined and neither is exit_early. I assume you will get to these eventually but just thought I'd help. Thanks again so much!

**Comment by ndepaola** [comment]
those two are defined in settings.jsx
